description: >
  Generates a set of pipeline parameters from `mapping` at
  `output-path`.

parameters:
  base-revision:
    type: string
    default: "main"
    description: >
      The revision to compare the current one against for the purpose
      of determining changed files.
  mapping:
    type: string
    default: ""
    description: >
      Mapping of path regular expressions to pipeline parameters and
      values. One mapping per line, whitespace-delimited.
  output-path:
    type: string
    default: "/tmp/pipeline-continuation.yml"
    description: >
      Path to save the generated continuation config to.
  files:
    type: string
    default: ""
    description: >
      Specify here the partial and non-partial configuration file(s)
      intended to be used on each build.
      Whitespace-delimited.

steps:
  - run:
      environment:
        BASE_REVISION: << parameters.base-revision >>
        MAPPING: << parameters.mapping >>
        OUTPUT_PATH: << parameters.output-path >>
        CONFIG_FILES: << parameters.files >>
      name: Merge configuation files
      shell: /usr/bin/env python3
      command: <<include(scripts/create-parameters.py)>>
